version: "3.8"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./InfoCompanies-Data-Model:/csv
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 8180
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8180'
      start_interval: 10s

  scraping:
    build: ./InfoCompanies-Scraping-API
    env_file:
      - ./InfoCompanies-Scraping-API/.env

  backend:
    build: ./InfoCompanies-API
    env_file:
      - ./InfoCompanies-API/.env
    depends_on:
      - keycloak
      - postgres

  frontend:
    build:
      context: ./InfoCompanies-Front
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./InfoCompanies-Front/.env
    depends_on:
      - backend
      - oauth2-proxy

  redis:
    image: redis
    ports:
      - "6379:6379"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
      OAUTH2_PROXY_CLIENT_ID: "spring-ba-infocompanies"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost/oauth2/callback"
      # Find the client secret in realm-export.json
      OAUTH2_PROXY_CLIENT_SECRET: "OMMsZCibSNfZemo6iwjg6mOziicG1FJf"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak:8180/realms/infoCompanies"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: "iCg-xr79FO66_EiOhZF3pOsEGnNfARiH50MX0AWaBU8="
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_REFRESH: "59m"
      OAUTH2_PROXY_COOKIE_EXPIRE: "168h"
      OAUTH2_PROXY_COOKIE_DOMAIN: "localhost"
      OAUTH2_PROXY_UPSTREAMS: "http://backend:8080/"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
      OAUTH2_PROXY_REDIS_CONNECTION_URL: "redis://redis:6379"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"
      OAUTH2_PROXY_LOG_LEVEL: debug
      OAUTH2_PROXY_LOG_FORMAT: json
    command:
      - --whitelist-domain=localhost
      - --whitelist-domain=localhost:3000
      - --whitelist-domain=localhost:80
      - --insecure-oidc-allow-unverified-email=true
      - --prefer-email-to-user=true
      - --set-xauthrequest=true
      - --skip-provider-button=true
    depends_on:
      keycloak:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  pgadmin_data:
