FROM python:3.9

WORKDIR /app

# Install Python dependencies
COPY ./devcli-scripts/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy script files
COPY ./devcli-scripts .

# Copy .env file to root directory
COPY .env /app/.env
RUN chmod 777 /app/.env

ENTRYPOINT ["python3", "fetch_keycloak_secret.py"]

